### ISSUE TITLE
Update topnav for "MBON Portal Documentation"

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/documentation-theme-jekyll#2]
The "MBON Portal Documentation" text should be changed to "MBON Data and File Formatting".

![image](https://user-images.githubusercontent.com/8480023/216132533-bd927984-5d17-42cb-ba0a-63ae78469fdb.png)

I think this is an easy adjustment to make to https://ioos.github.io/ but I have no clue how to get it to propagate to all the subsequent sites. I know we are using GH modules, so does each repo need to fetch the most recent commit to wherever the top nav info is pulling from?

@mwengren I can write down the process if we can work through it. 

edit: updated screenshot

**Comment by mwengren** [comment]
Ugh.  It's a repeatable process that at one point I wrote a script for, but I admit I'm rusty on it since it's been awhile.   I'll try to dig it up.    It's basically just a `git submodule update, git commit` repeated across each of the repos.  

I probably need to update my list of the various IOOS Documentation repos.  Maybe there's a way we can maintain a repo inventory somewhere we could pull from?

**Comment by MathewBiddle** [comment]
wonder if we could add a cron job using GH-actions to update these for each of the relevant repos?

Sounds like a fun activity ;)

**Comment by mwengren** [comment]
That would be a better way to do it.  That's beyond my GHA skills to do though.  If we could add a once a month check or something that failed silently if there weren't any upstream changes, hopefully that would get the job done.  Want to take a crack at it?

I found my script.  There's a little bit of checking done for differences between some of the documentation repos (a different branch name used for ioos.github.io basically), but it's pretty simple, I just run the following in a loop over each of our doc repos:

```
git submodule update --remote
git commit -am "Update remote submodules"
```
And then push the changes back up via `git push upstream $branch` depending on the branch name used. 

Since I'm running it locally I also have a checkout/pull routine before the git submodule commands, but that shouldn't be necessary for GHA.

I can email you the script if you want, but that's all it really is.  You'll see that commit message appear a few times in each repo the last I made changes to the site-wide nav bar.

On a related note, I remembered you submitted this issue ioos/ioos-documentation-jekyll-skeleton#4 awhile ago.  

I can't tell what the problem might be there or what your workflow is, but it seems as though there's something amiss.  I don't think it's necessary to do those steps, the `git submodule update` command should do it from within the forked version of the skeleton repo.  The steps you listed resemble what I did when first configuring the documentation repos, and the skeleton, and I don't think it needs to be repeated on each newly forked repo.

Maybe the `--merge` flag is the problem?  I removed it my script, maybe that was why...

Hopefully we can sort that issue out at the same time.

**Comment by mwengren** [comment]
If you get a chance to try to tackle this, there are a number of changes in addition to the MBON renaming we should make in the header.  A list to start with:

- Rename 'DMAC Implementation Standards...' to IOOS Data Standards & Requirements', change URL to: https://ioos.noaa.gov/data/data-standards/
- Rename IOOS Data Demo Center, update URL
- Remove the following sites/links (or perhaps move to an archive or deprecated list, see below): IOOS SOS Guidelines, IOOS Data Encoding TSV/CSV, IOOS Controlled Vocabularies)
- Remove software links: IOOS 52N SOS, IOOS ncSOS

Maybe we should consider reorganizing the header/menus entirely into different categories (names are just suggestions): 

- Data Standards 
  - all current, future data standards would go here
  - retain: Passive Acoustics
  - add https://ioos.github.io/ioos-atn-data/
- Software & Data Access
  - Compliance Checker
  - ioos_qc
  - erddapy
  - gliderpy
  - IOOS Code Lab
  - Cloud Sandbox
  - add https://ioos.github.io/erddap-gold-standard/
- Inactive/Deprecated Resources (?)
  - SOS stuff & the other data standard pages mentioned above? 
- ?

**Comment by MathewBiddle** [comment]
I think it's this file that needs to be updated: https://github.com/ioos/documentation-theme-jekyll/blob/navbars/topnav_ioos.yml

**Comment by MathewBiddle** [comment]
So, the top_navbars are pulled in as `git submodule` from the branch `navbars` in the documenation-theme-jekyll repository. That took me a bit to decipher.

From doing some sleuthing, I think we can add some `git` stuff to our github action to pull in recent updates to submodules.
See https://github.com/marketplace/actions/checkout-submodules#alternatives. 

Specifically:
```yaml
steps:
- name: Checkout repository and submodules
  uses: actions/checkout@v2
  with:
    submodules: recursive
```

I'll do some tinkering with https://github.com/ioos/mbon-docs to see what I can come up with.

**Comment by MathewBiddle** [comment]
As far as your comment
> I can't tell what the problem might be there or what your workflow is, but it seems as though there's something amiss. I don't think it's necessary to do those steps, the git submodule update command should do it from within the forked version of the skeleton repo. The steps you listed resemble what I did when first configuring the documentation repos, and the skeleton, and I don't think it needs to be repeated on each newly forked repo.

Yes, I agree it shouldn't have been that complicated. The reason I had to do all that workaround was because I wasn't forking the repo. I was cloning it, removing all the git tracking (which had the submodule refs) and moving the jekyll stuff into an orphaned gh-pages branch on an existing repo. This was all because I was starting from an existing repo without this stuff in it, so I had to add all of these pieces in manually. 

Maybe removing the `--merge` flag would fix it. But, I seem to recall there being some hiccups with that, hence the workaround.

**Comment by mwengren** [comment]
Close?

**Comment by MathewBiddle** [comment]
yes!
